name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*

  paths:
    exclude:
     - doc
     - ReadME.md

pr:
  branches:
    include:
    - main

variables:
- name: vmImage
  value: 'windows-latest'

stages:
- stage: SetupTemplates
  jobs:
  - job: 'SetupTemplates'
    pool:
      vmImage: ${{variables.vmImage}}
    steps:
    - template: 'publishtemplates.yaml'

- stage: DEV
  dependsOn: ['SetupTemplates']
  jobs:
  - deployment: DEV
    variables:
    - template: 'Variables/common.yaml'
    - template: 'Variables/dev.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'  
            parameters:
              buildNumber: $(Build.BuildNumber)      

- stage: TEST
  dependsOn: ['DEV']
  jobs:
  - deployment: TEST
    variables:
    - template: 'Variables/common.yaml'
    - template: 'Variables/test.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: TEST
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'  
            parameters:
              buildNumber: $(Build.BuildNumber)    

- stage: UAT
  dependsOn: ['TEST']
  jobs:
  - deployment: UAT
    variables:
    - template: 'Variables/common.yaml'
    - template: 'Variables/uat.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'  
            parameters:
              buildNumber: $(Build.BuildNumber)    

- stage: PT
  dependsOn: ['TEST']
  jobs:
  - deployment: PT
    variables:
    - template: 'Variables/common.yaml'
    - template: 'Variables/pt.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: PT
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'  
            parameters:
              buildNumber: $(Build.BuildNumber)                                           

- stage: PROD
  dependsOn: ['UAT', 'PT']
  jobs:
  - deployment: PROD
    variables:
    - template: 'Variables/common.yaml'
    - template: 'Variables/prod.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'  
            parameters:
              buildNumber: $(Build.BuildNumber)                                             